class: Project
properties:
  projectId: int
  accountId: int
  accountName: string
  builds:
    type: array
    annotations:
      collection: Build
  name: string
  slug: string
  repositoryType: string
  repositoryScm: string
  repositoryName: string
  repositoryBranch: string
  isPrivate: bool
  skipBranchesWithoutAppveyorYml: bool
  enableSecureVariablesInPullRequests: bool
  enableDeploymentInPullRequests: bool
  rollingBuilds: bool
  alwaysBuildClosedPullRequests: bool
  nuGetFeed: array
  securityDescriptor: array
  created: DateTimeInterface
  updated: DateTimeInterface
